spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://47.100.52.183:3306/meetingmanage?serverTimezone=UTC&characterEncoding=UTF-8
  jpa:
    show-sql: true
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
logging:
  level:
    com.seven.bootjpa: debug
server:
  port: 8088